name: draw_primitive
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^0.1.0
  vector_math: any
  umiuni2d:
    path: ../../../umiuni2d/core
  umiuni2d.flutter:
    path: ../../../umiuni2d/flutter
  umiuni2d.webgl:
    path: ../../../umiuni2d/webgl
  flutter:
    path: /Users/kyorohiro/tools/git/flutter/packages/flutter
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
- dart_to_js_script_rewriter
